#!/bin/bash

# Check if any .tar.gz files are present in the current directory
TAR_FILES=(*.tar.gz)

if [ ${#TAR_FILES[@]} -eq 0 ]; then
  echo "No .tar.gz files found in the current directory."
  exit 1
fi

# Use the first .tar.gz file found in the current directory
TAR_FILE="${TAR_FILES[0]}"

# Define other variables
JSON_FILE="users_000001.json"
NEW_JSON_FILE_LOCATION="/home/ec2-user/json-file/users_000001.json" # Update this to the correct path of the new JSON file

# Untar the .tar.gz file
tar -xzvf "$TAR_FILE"

# Output a message indicating the extraction is complete
echo "Extraction of $TAR_FILE is complete."

# Locate the JSON file (assuming it's in the root of the extracted directory)
EXTRACTED_DIR=$(tar -tzf "$TAR_FILE" | head -1 | cut -f1 -d"/")

# Check if the JSON file exists
if [ -f "$EXTRACTED_DIR/$JSON_FILE" ]; then
  echo "JSON file exists."

  # Remove the original JSON file
  rm "$EXTRACTED_DIR/$JSON_FILE"
  echo "Original JSON file has been removed."

  # Copy the new JSON file from the specified location
  cp "$NEW_JSON_FILE_LOCATION" "$EXTRACTED_DIR/"
  echo "New JSON file has been copied from '$NEW_JSON_FILE_LOCATION' to '$EXTRACTED_DIR/'."

  # Re-tar the directory into a .tar.gz file with timestamp
  TIMESTAMP=$(date +%Y%m%d_%H%M%S)
  NEW_TAR_FILE="${EXTRACTED_DIR}_updated_${TIMESTAMP}.tar.gz"
  tar -czvf "$NEW_TAR_FILE" -C "$EXTRACTED_DIR" .

  # Changing ownership of the new tar file
  echo "Changing ownership of the new tar file to ec2-user"
  chown ec2-user:ec2-user "$NEW_TAR_FILE"

  # Move the new tar file to the current directory
  mv "$NEW_TAR_FILE" .

else
  echo "JSON file '$JSON_FILE' not found."
fi
