#!/bin/bash

# Run the Docker container in detached mode
docker run -d --name gl-exporter-container github/gl-exporter /bin/bash

# Wait for the container to be fully started
sleep 5

# Execute commands inside the running container
docker exec gl-exporter-container /bin/bash -c "./env && gl_exporter -f export.csv -o migration-archive.tar.gz"

# Optionally, you can remove the container after execution
docker rm -f gl-exporter-container
